language: android
android:
  components:
    - build-tools-20.0.0
    - android-L
    - extra
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

install:
 - ./gradlew assemble
