language: android
android:
  components:
    - build-tools-20.0.0
    - android-L
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

install:
 - ./gradlew assemble
